#!/usr/bin/env bash
# Installs nginx on web server
# and set /redirect_me to another page

# update package lists for upgrades
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# start Nginx
sudo service nginx start

# create a simple html file
echo "Hello World!" > /var/www/html/index.html

# configure nginx to redirect /redirect_me to another page
# sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sudo sed -i '24i\    rewrite ^/redirect_me https://www.google.com/ permanent;' /etc/nginx/sites-available/default 

# restart nginx
sudo service nginx restart
