#!/usr/bin/env bash
# Installs nginx on web server and configures custom 404 page

# Update package lists for upgrades
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Start Nginx
sudo service nginx start

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.html

# configure nginx to redirect /redirect_me to another page
# file="/etc/nginx/sites-available/default"
# new_string="location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }"
# sudo sed -i "/server_name _;/a \    $new_string" $file 
sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-enabled/default

# create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# configure nginx to use the custom 404 page
echo "error_page 404 /404.html;" >> /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
