#!/usr/bin/env bash
# Installs nginx on web server and configures custom 404 page

# Update package lists for upgrades
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Start Nginx
sudo service nginx start

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.html

# configure nginx to redirect /redirect_me to another page
# file="/etc/nginx/sites-available/default"
# new_string="location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }"
# sudo sed -i "/server_name _;/a \    $new_string" $file 

echo "Ceci n'est pas une page" | sudo tee "/usr/share/nginx/html/404.html"

# Restore default error page configurations
sudo sed -i '/error_page 404/c\    error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '/location \= \/404.html/c\    location = \/404.html {\n        root \/usr\/share\/nginx\/html;\n        internal;\n    }' /etc/nginx/sites-available/default
# restart nginx
sudo service nginx restart
