#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header

# update package lists for upgrades
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

HOSTNAME=$(hostname)

# create a configuration snippet to add the custom header
echo "add_header X-Served-By $HOSTNAME;" > /etc/nginx/snippets/custom_header.conf

# use sed to add custom header to config file
sudo sed -i '/server_name _;/a include snippets/custom_header.conf;' /etc/nginx/sites-available/default

# test configuration and restart server
sudo nginx -t

sudo service nginx restart
