#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header

# update package lists for upgrades
sudo apt-get update 

# Install nginx if not installed
sudo apt-get install -y nginx

HOSTNAME=$(hostname)

# use sed to add custom header to config file
sudo sed -i "/location \/ {/a\        add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# test configuration and restart server
sudo nginx -t

if [ $? -eq 0 ]
then
    sudo service nginx restart
fi
