#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header

# update package lists for upgrades
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# variables
NGINX_CONFIG="/etc/nginx/sites-available/default"
SERVER_NAME=$(hostname)

# define custom header
CUSTOM_HEADER="add_header X-Served-By '$SERVER_NAME';"

# use sed to add custom header to config file
sudo sed -i "/server_name _;/a\ \ \ \ $CUSTOM_HEADER" $NGINX_CONFIG

# test configuration and restart server
sudo nginx -t

sudo service nginx restart
