#!/usr/bin/env bash
# This script installs and configures HAProxy

# Update package lists for upgrades
sudo apt-get -y update 

# Enable a dedicated PPA
sudo apt-get install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update

# Install HAProxy
sudo apt-get install -y haproxy

# Backup the original configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new configuration file
echo "
frontend http_front
   bind *:80
   mode http
   default_backend http_back

backend http_back
   balance roundrobin
   server 512863-web-01 34.204.95.239:80 check
   server 512863-web-02 54.234.17.205:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo service haproxy restart
