#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but
#+ displays bad luck for the 4th iteration and good luck for
#+ the 8th iteration

a=0
while [ $a -lt 10 ]
do
    ((a++))
    if [ $a -eq 4 ]
    then
        echo "bad luck"
    elif [ $a -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi 
done