#!/usr/bin/env bash
# This script that displays all active IPv4 IPs on the machine

interfaces=$(ls /sys/class/net)

for interface in $interfaces
do

    ip=$(ip -4 -o addr show "$interface" | awk '{split($4,a,"/");print a[1]}')

    if [ -n "$ip" ]
    then
        echo "$ip"
    fi
done