#!/usr/bin/env bash
# This script configures a container to run nginx as ngix user
# and listens to all active IPs on port 8080

# Change the user and group in the Nginx configuration
sudo sed -i 's/user  www-data;/user  nginx;/' /etc/nginx/nginx.conf

# Modify Nginx configuration to listen on all IPs on port 8080
sudo sed -i 's/listen       80;/listen       8080;/' /etc/nginx/conf.d/default.conf

chmod 644 /etc/nginx/nginx.conf
# Restart Nginx to apply the changes
sudo -u nginx service nginx restart

echo "Nginx has been successfully configured and restarted"