#!/usr/bin/env bash
# This script configures a container to run nginx as nginx user and listens to all active IPs on port 8080
sed -i 's/user root;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
echo "Nginx has been successfully configured and restarted"
